//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="AutonomusDrive.Y2013.M08, Version=0.0.0.0, Culture=neutral, PublicKeyToken=779fc1" +
    "78f5d07eb3")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformAutonomusDrive {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.AutonomusDrive.Diagram.Proxy.ActionRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_AutonomusDrive_Diagram_Proxy_ActionRequest_TO_Robotics_AutonomusDrive_Diagram_ActionRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.AutonomusDrive.Diagram.ActionRequest), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_AutonomusDrive_Diagram_ActionRequest_TO_Robotics_AutonomusDrive_Diagram_Proxy_ActionRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.AutonomusDrive.Diagram.Proxy.ActionResponse), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_AutonomusDrive_Diagram_Proxy_ActionResponse_TO_Robotics_AutonomusDrive_Diagram_ActionResponse));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.AutonomusDrive.Diagram.ActionResponse), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_AutonomusDrive_Diagram_ActionResponse_TO_Robotics_AutonomusDrive_Diagram_Proxy_ActionResponse));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::Robotics.AutonomusDrive.Diagram.Proxy.DiagramState), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_AutonomusDrive_Diagram_Proxy_DiagramState_TO_Robotics_AutonomusDrive_Diagram_DiagramState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::Robotics.AutonomusDrive.Diagram.DiagramState), new global::Microsoft.Dss.Core.Attributes.Transform(Robotics_AutonomusDrive_Diagram_DiagramState_TO_Robotics_AutonomusDrive_Diagram_Proxy_DiagramState));
        }
        
        private static global::Robotics.AutonomusDrive.Diagram.Proxy.ActionRequest _cachedInstance0 = new global::Robotics.AutonomusDrive.Diagram.Proxy.ActionRequest();
        
        private static global::Robotics.AutonomusDrive.Diagram.ActionRequest _cachedInstance = new global::Robotics.AutonomusDrive.Diagram.ActionRequest();
        
        public static object Robotics_AutonomusDrive_Diagram_Proxy_ActionRequest_TO_Robotics_AutonomusDrive_Diagram_ActionRequest(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object Robotics_AutonomusDrive_Diagram_ActionRequest_TO_Robotics_AutonomusDrive_Diagram_Proxy_ActionRequest(object transformFrom) {
            return _cachedInstance0;
        }
        
        private static global::Robotics.AutonomusDrive.Diagram.Proxy.ActionResponse _cachedInstance2 = new global::Robotics.AutonomusDrive.Diagram.Proxy.ActionResponse();
        
        private static global::Robotics.AutonomusDrive.Diagram.ActionResponse _cachedInstance1 = new global::Robotics.AutonomusDrive.Diagram.ActionResponse();
        
        public static object Robotics_AutonomusDrive_Diagram_Proxy_ActionResponse_TO_Robotics_AutonomusDrive_Diagram_ActionResponse(object transformFrom) {
            return _cachedInstance1;
        }
        
        public static object Robotics_AutonomusDrive_Diagram_ActionResponse_TO_Robotics_AutonomusDrive_Diagram_Proxy_ActionResponse(object transformFrom) {
            return _cachedInstance2;
        }
        
        private static global::Robotics.AutonomusDrive.Diagram.Proxy.DiagramState _cachedInstance4 = new global::Robotics.AutonomusDrive.Diagram.Proxy.DiagramState();
        
        private static global::Robotics.AutonomusDrive.Diagram.DiagramState _cachedInstance3 = new global::Robotics.AutonomusDrive.Diagram.DiagramState();
        
        public static object Robotics_AutonomusDrive_Diagram_Proxy_DiagramState_TO_Robotics_AutonomusDrive_Diagram_DiagramState(object transformFrom) {
            return _cachedInstance3;
        }
        
        public static object Robotics_AutonomusDrive_Diagram_DiagramState_TO_Robotics_AutonomusDrive_Diagram_Proxy_DiagramState(object transformFrom) {
            return _cachedInstance4;
        }
    }
}
